package com.peiyu.mem.domian.entity;

import java.io.Serializable;
import java.util.Date;

/**
 * Created by Administrator on 2016/11/29.
 * 优惠券使用范围
 */
public class CpUseLimitdt implements Serializable {
    /**
     *记录编号<br/>
     **/
    private Long id;

    /**
     *商家ID<br/>
     **/
    private Long vendorId;

    /**
     *主记录编码(如主记录类型为活动应保存actCode, 如主记录为优惠券组应保存subgroupCode)<br/>
     **/
    private String ownRecordCode;

    /**
     *主记录类型(0-活动, 1-优惠券组)<br/>
     **/
    private Integer ownRecordType;

    /**
     *使用范围类型(0-不限制, 1-机构, 2-门店)<br/>
     **/
    private Integer useScopeType;

    /**
     *机构编码<br/>
     **/
    private String organCode;

    /**
     *机构名称<br/>
     **/
    private String organName;

    /**
     *门店编码<br/>
     **/
    private String storeCode;

    /**
     *门店名称<br/>
     **/
    private String storeName;

    /**
     *备注<br/>
     **/
    private String memo;

    /**
     *创建日期<br/>
     **/
    private Date createDate;

    /**
     *修改日期<br/>
     **/
    private Date modifyDate;

    /**
     *记录创建人用户名<br/>
     **/
    private String creator;

    /**
     *是否已删除1删除 0正常<br/>
     **/
    private Integer df;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cpuselimitdt
     *
     * @mbggenerated Wed Sep 16 16:38:09 CST 2015
     */
    private static final long serialVersionUID = 1L;

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getVendorId() {
        return vendorId;
    }

    public void setVendorId(Long vendorId) {
        this.vendorId = vendorId;
    }

    public String getOwnRecordCode() {
        return ownRecordCode;
    }

    public void setOwnRecordCode(String ownRecordCode) {
        this.ownRecordCode = ownRecordCode == null ? null : ownRecordCode.trim();
    }

    public Integer getOwnRecordType() {
        return ownRecordType;
    }

    public void setOwnRecordType(Integer ownRecordType) {
        this.ownRecordType = ownRecordType;
    }

    public Integer getUseScopeType() {
        return useScopeType;
    }

    public void setUseScopeType(Integer useScopeType) {
        this.useScopeType = useScopeType;
    }

    public String getOrganCode() {
        return organCode;
    }

    public void setOrganCode(String organCode) {
        this.organCode = organCode == null ? null : organCode.trim();
    }

    public String getOrganName() {
        return organName;
    }

    public void setOrganName(String organName) {
        this.organName = organName == null ? null : organName.trim();
    }

    public String getStoreCode() {
        return storeCode;
    }

    public void setStoreCode(String storeCode) {
        this.storeCode = storeCode == null ? null : storeCode.trim();
    }

    public String getStoreName() {
        return storeName;
    }

    public void setStoreName(String storeName) {
        this.storeName = storeName == null ? null : storeName.trim();
    }
    public String getMemo() {
        return memo;
    }

    public void setMemo(String memo) {
        this.memo = memo == null ? null : memo.trim();
    }

    public Date getCreateDate() {
        return createDate;
    }

    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    public Date getModifyDate() {
        return modifyDate;
    }

    public void setModifyDate(Date modifyDate) {
        this.modifyDate = modifyDate;
    }

    public String getCreator() {
        return creator;
    }

    public void setCreator(String creator) {
        this.creator = creator == null ? null : creator.trim();
    }

    public Integer getDf() {
        return df;
    }

    public void setDf(Integer df) {
        this.df = df;
    }


}
